//@version=5
indicator(title="Indicator tutorial", overlay=true)

src = input.source(close, "source")
MA_type = input.string("SMA", "MA type")
MA_window = input.int(20, "MA window")
color = input.color(color.red, "Color MA")

int series1 = 0
float series2 = 1.0
bool series3 = false
string series4 = "ok"
series2 := 1
series3 := true

var int count = 0
var bool var2 = true

ma = ta.sma(close, 10)
// plot(ma, color=color.red)
rsi = ta.rsi(close, 14)
[basis, upper, lower] = ta.bb(close, 20, 1)
highestHigh = ta.highest(high, 20)

impulsion = (low - high[2]) / high[2] > 1.0 / 100

MA_function(src, MA_type, MA_length) => 
    if MA_type == 'SMA'
        ta.sma(src, MA_length)
    else if MA_type == 'EMA'
        ta.ema(src, MA_length)
    else if MA_type == 'WMA'
        ta.wma(src, MA_length)
    else
        na
    MA_type == 'SMA' ? ta.sma(src, MA_length) : MA_type == 'EMA' ? ta.ema(src, MA_length) : MA_type == 'WMA' ? ta.wma(src, MA_length) : na

MA = MA_function(src, MA_type, MA_window)
plot(MA, color=color)

bool isMidnight = (hour(time, "UTC+1")==0) and (minute(time,"UTC+1")==0)
if (isMidnight)
    line.new(bar_index, low, bar_index, high, xloc.bar_index, extend.both, color.blue, line.style_dotted, 1)

period = timeframe.period
nb_seconds_per_candle = timeframe.in_seconds()
